### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by vkbishnoi** [Dynatrace/OneAgent-SDK-for-C#1]
Hi,

I am trying to use this SDK in our C++ application. Call to onesdk_initialize() is always failing with a return value of 126 which is "a specified module could not be found".
When I open "onesdk_shared.dll" in Dependency Walker, It shows me multiple errors of missing dependencies. Few of them are 
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-1.DLL

Also some more errors

Error: At least one required implicit or forwarded dependency was not found.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.

I am using a Widows 10 machine with Visual Studio 2015 installed on it. Also I have VC++ redistributable also installed.

**Comment by vkbishnoi** [comment]
Hi,
Thanks for your reply. 
I have DynaTrace OneAgent installed in my laptop.  Version number is "Dynatrace-OneAgent-Windows-1.147.152". I can see the service up and running.
Do I have to install something else as well for the SDK to work? Or set some path in environment variable??

**Comment by AlramLechnerDynatrace** [comment]
Hi,
Thanks for your reply. In the case Dynatrace OneAgent is already installed, please open a support ticket at https://support.dynatrace.com. In that way, we are able to analyze and track the issue with our support tools.

About your question: no, there is no need for additional libraries or any environment variable. First we need to analyze the logfiles from your system. For details checkout https://www.dynatrace.com/support/help/installation/setup-tips/where-can-i-find-oneagent-files-and-logs/.

BR
Alram

**Comment by vkbishnoi** [comment]
Hi Alram,
I can see lot of log files. Could you please tell me which one I should check for this issue?

-Vishal

**Comment by AlramLechnerDynatrace** [comment]
Hi Vishal,
All logfiles from the subfolders
- process
- os
- sdk (if it exist)
are of interest for us.
BR
Alram

**Comment by SonjaChevre** [comment]
Hi Vishal,

we haven't heard from you in a while so I'm closing this ticket. Let us know if you need any additional help.

Sonja
