### ISSUE TITLE
Oneagent installation without success S.O Solaris

### ISSUE THREAD

**Issue by Favistar** [Dynatrace/OneAgent-SDK-for-C#14]
The Oneagent was configured in S.O Solaris, the tenant and tokentenant variables were configured in the application in C, inserting the SDK. However, nothing is displayed in Dynatrace. Evidence of RED and the configurations that were made are attached. Please your urgent support. Also, the logs are attached.

[unibanca may22 (2).zip](https://github.com/Dynatrace/OneAgent-SDK-for-C/files/8742430/unibanca.may22.2.zip)

**Comment by z1c0** [comment]
Please contact your Dynatrace support person if the problem persists.
