### ISSUE TITLE
Handle inbound web request asynchronously

### ISSUE THREAD

**Issue by qfsmike** [Dynatrace/OneAgent-SDK-for-C#7]
I'm trying to add tracing to an ISAPI DLL in C/C++ on Windows.

I'm creating a top level tracer in HttpExtensionProc using onesdk_incomingwebrequesttracer_create followed by onesdk_tracer_start.

I then reach a point at which I know the request is not going to be satisfied in the current thread and allocate a link blob using onesdk_inprocesslink_create.  The rest of the processing will resume in a thread pool thread when resources are available.

I'm confused as to the state of the current tracer created by onesdk_incomingwebrequesttracer_create.  If I try to call onesdk_tracer_end immediately after creating the link I see an exception thrown (and handled within the SDK) -
    boost::wrapexcept<technology::sdk::WrongNodeStateException>

...so I presume this is the wrong thing to do?  If I continue to do that I see the request logged in a PurePath but with a warning icon to indicate data loss, presumably related to the exception.

If I leave the tracer in the main thread and then carry on with the request in a worker thread and create another (the same?) tracer using onesdk_inprocesslinktracer_create the request is just not logged.

What is the best way to handle this kind of asynchronous work?

**Comment by arminru** [comment]
Hi qfsmike,

thanks for your request.
Did you already follow the troubleshooting steps stated in our readme (https://github.com/Dynatrace/OneAgent-SDK-for-C#troubleshooting)? The logging callback, once installed, should provide you with valuable details describing the exception you noticed. It would also be great if you could illustrate your case with a minimal code sample reproducing the problem.

I suppose you're ending the tracer before you are starting it. Please note that creating the tracer does not automatically start it - this has to be done manually once you want to start tracing.
Furthermore, you can only create an in-process link when you are on an active PurePath, i.e., between starting and ending the surrounding tracer.

The correct usage in your case would be (pseudo-code):

Thread 1:
```
web_tracer = onesdk_incomingwebrequesttracer_create()
onesdk_tracer_start(web_tracer)
// handle request
link = onesdk_inprocesslink_create()
// pass link to other thread for asynchronous handling
onesdk_tracer_end(web_tracer)
```

Thread 2:
```
ipl_tracer = onesdk_inprocesslinktracer_create(link)
onesdk_tracer_start(ipl_tracer)
// do stuff which you'd like to trace
onesdk_tracer_end(ipl_tracer)
```

Please also refer to the docs and our readme for further details:
https://github.com/Dynatrace/OneAgent-SDK-for-C#using-the-dynatrace-oneagent-sdk-to-trace-incoming-web-requests
https://github.com/Dynatrace/OneAgent-SDK-for-C#using-the-dynatrace-oneagent-sdk-to-trace-asynchronous-activities

Let me know if that solved your problem or if you need further assistance.

Best,
Armin

**Comment by qfsmike** [comment]
Hi Armin,

Thanks. 

I hadn't started the tracer in the worker thread after creating it.

The diagnostics seem to show up that the tracer is not 'top of the stack' so I'll have to address that.

I had enabled the logging callback previously but had put it before initialising the SDK so nothing ever came out.

Kind Regards,
Mike.

**Comment by arminru** [comment]
Thanks for the feedback, I'm glad I could help.

Best,
Armin
